title = "ChainBoard Configs - Example Full"

[database]
connectionUri = ""
databaseName = ""

[blockchains]
[blockchains.ethereum]
name = "ethereum"
family = "evm"
startBlock = 18895915
nodeRpcs = ["https://eth.llamarpc.com", "https://eth-pokt.nodies.app"]

[blockchains.arbitrum]
name = "arbitrum"
family = "evm"
startBlock = 0 # auto sync from recently 100 blocks
nodeRpcs = ["https://arbitrum.llamarpc.com"]

[blockchains.solana]
name = "solana"
family = "solana"
startBlock = 0
nodeRpcs = ["https://api.devnet.solana.com"]

[blockchains.sui]
name = "sui"
family = "sui"
startBlock = 0
nodeRpcs = ["https://fullnode.mainnet.sui.io"]
